package usecase_style

import (
	"github.com/a-h/templ"
	style "github.com/landmaster135/devbox/internal/templ_components/core/style"
)

func buildUsecaseStyle() (style.CSSStyle, error) {
	var buildErr error
	capture := func(css templ.SafeCSS, err error) templ.SafeCSS {
		if buildErr != nil {
			return ""
		}
		if err != nil {
			buildErr = err
			return ""
		}
		return css
	}

	css := style.CSSStyle{
		Rules: []style.CSSRule{
			style.Rule(":root",
				style.Property("color-scheme", "light dark"),
				capture(style.MustSafeFontFamily("font-family", []string{"Inter", "Segoe UI", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"})),
			),
			style.Rule("*",
				style.Property("box-sizing", "border-box"),
			),
			style.Rule("body",
				style.Property("margin", "0"),
				style.Property("background", "#f5f6fb"),
				capture(style.MustSafeColorProperty("color", "#111827")),
			),
			style.Rule("main.page",
				style.Property("max-width", "1100px"),
				style.Property("margin", "0 auto"),
				style.Property("padding", "48px 20px 80px"),
			),
			style.Rule(".hero",
				capture(style.MustSafeLinearGradient("background", "120deg", "#eef2ff", "#e0f2fe")),
				capture(style.MustSafeBorder("border", "1px", "solid", []string{"rgba(99, 102, 241, 0.25)"})),
				style.Property("border-radius", "20px"),
				style.Property("padding", "32px"),
				capture(style.MustSafeBoxShadow("box-shadow", []string{"0", "15px", "35px"}, []string{"rgba(15, 23, 42, 0.08)"})),
			),
			style.Rule(".hero-eyebrow",
				style.Property("text-transform", "uppercase"),
				style.Property("letter-spacing", "0.12em"),
				style.Property("font-size", "0.75rem"),
				capture(style.MustSafeColorProperty("color", "#6366f1")),
				style.Property("margin", "0 0 8px"),
			),
			style.Rule(".hero h1",
				style.Property("margin", "0 0 16px"),
				style.Property("font-size", "2rem"),
			),
			style.Rule(".hero-description",
				style.Property("margin", "0 0 12px"),
				capture(style.MustSafeColorProperty("color", "#374151")),
			),
			style.Rule(".hero-source,\n.hero-endpoint",
				style.Property("margin", "4px 0"),
				style.Property("font-size", "0.9rem"),
				capture(style.MustSafeColorProperty("color", "#4b5563")),
			),
			style.Rule(".hero code",
				capture(style.MustSafeColorProperty("background", "rgba(255, 255, 255, 0.8)")),
				style.Property("padding", "4px 8px"),
				style.Property("border-radius", "6px"),
			),
			style.Rule(".page-sections",
				style.Property("margin-top", "32px"),
				style.Property("display", "flex"),
				style.Property("flex-direction", "column"),
				style.Property("gap", "32px"),
			),
			style.Rule(".workflow-category",
				style.Property("background", "#ffffff"),
				style.Property("border-radius", "20px"),
				capture(style.MustSafeBorder("border", "1px", "solid", []string{"rgba(148, 163, 184, 0.4)"})),
				style.Property("padding", "28px"),
				capture(style.MustSafeBoxShadow("box-shadow", []string{"0", "20px", "45px"}, []string{"rgba(15, 23, 42, 0.06)"})),
			),
			style.Rule(".workflow-category__header > h2",
				style.Property("margin", "0 0 4px"),
			),
			style.Rule(".workflow-category__header > p",
				style.Property("margin", "0"),
				capture(style.MustSafeColorProperty("color", "#4b5563")),
			),
			style.Rule(".workflow-card",
				style.Property("background", "#f8fafc"),
				style.Property("border-radius", "16px"),
				capture(style.MustSafeBorder("border", "1px", "solid", []string{"rgba(203, 213, 225, 0.7)"})),
				style.Property("padding", "20px"),
				style.Property("display", "flex"),
				style.Property("flex-direction", "column"),
				style.Property("gap", "12px"),
			),
			style.Rule(".workflow-card__process",
				style.Property("margin", "0"),
				style.Property("font-size", "0.85rem"),
				capture(style.MustSafeColorProperty("color", "#6b7280")),
			),
			style.Rule(".workflow-card__process code",
				capture(style.MustSafeColorProperty("background", "rgba(255, 255, 255, 0.75)")),
				style.Property("padding", "2px 6px"),
				style.Property("border-radius", "5px"),
			),
			style.Rule(".workflow-card__header h3",
				style.Property("margin", "6px 0 0"),
			),
			style.Rule(".workflow-card__summary",
				style.Property("margin", "0"),
				capture(style.MustSafeColorProperty("color", "#475569")),
				style.Property("line-height", "1.4"),
			),
			style.Rule(".workflow-card__cron",
				style.Property("display", "flex"),
				style.Property("flex-direction", "column"),
				style.Property("font-size", "0.9rem"),
			),
			style.Rule(".workflow-card__cron span",
				style.Property("font-weight", "600"),
				capture(style.MustSafeColorProperty("color", "#0f172a")),
			),
			style.Rule(".workflow-card__cron code",
				style.Property("margin-top", "4px"),
				style.Property("padding", "4px 6px"),
				capture(style.MustSafeColorProperty("background", "#e2e8f0")),
				style.Property("border-radius", "6px"),
				capture(style.MustSafeFontFamily("font-family", []string{"JetBrains Mono", "SFMono-Regular", "Consolas", "monospace"})),
			),
			style.Rule(".workflow-card__manual",
				style.Property("margin-top", "auto"),
				style.Property("display", "flex"),
				style.Property("justify-content", "flex-start"),
			),
			style.Rule(".workflow-card__manual button",
				style.Property("padding", "10px 16px"),
				capture(style.MustSafeColorProperty("background", "#4f46e5")),
				style.Property("color", "#ffffff"),
				style.Property("border", "none"),
				style.Property("border-radius", "8px"),
				style.Property("cursor", "pointer"),
				style.Property("font-weight", "600"),
			),
			style.Rule(".workflow-card__manual button:hover",
				capture(style.MustSafeColorProperty("background", "#4338ca")),
			),
			style.Rule(".workflow-card__status",
				style.Property("font-size", "0.85rem"),
				style.Property("margin", "8px 0 0"),
				style.Property("min-height", "1.2em"),
				capture(style.MustSafeColorProperty("color", "#4b5563")),
			),
			// TODO: 動的に反映されるようにする
			style.Rule(".workflow-card__status[data-status=\"success\"]",
				capture(style.MustSafeColorProperty("color", "#0f766e")),
			),
			style.Rule(".workflow-card__status[data-status=\"error\"]",
				capture(style.MustSafeColorProperty("color", "#dc2626")),
			),
			style.Rule(".workflow-card__status[data-status=\"pending\"]",
				capture(style.MustSafeColorProperty("color", "#92400e")),
			),
			style.Rule(".empty-state",
				style.Property("margin-top", "32px"),
				style.Property("padding", "40px"),
				style.Property("text-align", "center"),
				style.Property("border-radius", "16px"),
				capture(style.MustSafeBorder("border", "1px", "dashed", []string{"rgba(99, 102, 241, 0.5)"})),
				capture(style.MustSafeColorProperty("color", "#4b5563")),
			),
		},
		MediaRules: []style.CSSMediaRule{
			style.Media("(prefers-color-scheme: dark)",
				style.Rule("body",
					capture(style.MustSafeColorProperty("background", "#020617")),
					style.Property("color", "#e2e8f0"),
				),
				style.Rule(".hero",
					capture(style.MustSafeLinearGradient("background", "120deg", "#312e81", "#1d4ed8")),
					capture(style.MustSafeBorder("border", "1px", "solid", []string{"rgba(99,102,241,0.5)"})),
				),
				style.Rule(".hero-description, .hero-source, .hero-endpoint",
					capture(style.MustSafeColorProperty("color", "#cbd5f5")),
				),
				style.Rule(".workflow-category",
					capture(style.MustSafeColorProperty("background", "#0f172a")),
					capture(style.MustSafeBorder("border", "1px", "solid", []string{"rgba(59, 130, 246, 0.4)"})),
				),
				style.Rule(".workflow-card",
					capture(style.MustSafeColorProperty("background", "#1e293b")),
					capture(style.MustSafeBorder("border", "1px", "solid", []string{"rgba(59, 130, 246, 0.25)"})),
				),
				style.Rule(".workflow-card__summary",
					capture(style.MustSafeColorProperty("color", "#cbd5f5")),
				),
				style.Rule(".workflow-card__cron span",
					capture(style.MustSafeColorProperty("color", "#f8fafc")),
				),
				style.Rule(".workflow-card__cron code",
					capture(style.MustSafeColorProperty("background", "#0f172a")),
				),
				style.Rule(".empty-state",
					capture(style.MustSafeBorder("border", "1px", "dashed", []string{"rgba(99, 102, 241, 0.8)"})),
					capture(style.MustSafeColorProperty("color", "#cbd5f5")),
				),
			),
		},
	}

	if buildErr != nil {
		return style.CSSStyle{}, buildErr
	}
	return css, nil
}
