services:
  devbox:
    image: "devbox-cron:latest"
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      - GIN_MODE=staging
    volumes:
      - type: bind
        source: ""
        target: ""
    user: "9999:9999"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "devbox"
      tsdproxy.container_port: 9999
