version: "3"

tasks:
  default:
    desc: "デフォルト実行タスク"
    cmds:
      - task: test:all:cov
      - task: build
      - task: build:mcp
  alias:
    desc: "タスク一覧表示"
    cmds:
      - task --list-all
  find:docs:
    desc: ""
    cmds:
      - find docs | sort -f
  find:agents:
    desc: ""
    cmds:
      - find .agents | sort -f
  find:pjroot:
    desc: ""
    cmds:
      - find . -maxdepth 1 -type f | sort -f
  find:sql:
    desc: ""
    cmds:
      - echo 'No registered command...'
  run:dev:
    desc: ""
    cmds:
      - go run {{ .DIR }}
    vars:
      DIR: ./cmd/cli/{{ .CLI_ARGS }}
  run:tee:
    desc: ""
    cmds:
      - go run {{ .DIR }} | tee
    vars:
      DIR: ./cmd/cli/{{ .CLI_ARGS }}
  run:backend:
    desc: ""
    cmds:
      - echo 'No registered command...'
  check:
    desc: ""
    cmds:
      - go vet ./...
  test:cov:
    desc: ""
    cmds:
      - go test -cover
  test:all:cov:
    desc: ""
    cmds:
      - go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out && go tool cover -html=coverage.out -o coverage.html
  test:all:out:
    desc: ""
    cmds:
      - go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out && go tool cover -html=coverage.out -o coverage.html
  build:
    desc: ""
    cmds:
      - ./scripts/build/build.sh
  build:dev:
    desc: ""
    cmds:
      - echo 'No registered command...'
  build:pre:
    desc: ""
    cmds:
      - ./scripts/initialize/script_generator_to_build.sh {{ .CLI_ARGS }}
  build:mcp:
    desc: ""
    cmds:
      - ./scripts/build/build_mcp_tools.sh
  domain:mig:new:
    desc: ""
    cmds:
      - ./scripts/initialize/create_project_files.sh {{ .CLI_ARGS }}
  domain:mig:run:
    desc: ""
    cmds:
      - echo 'No registered command...'
