// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package weather_notificator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WeatherNotificatorServiceClient is the client API for WeatherNotificatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherNotificatorServiceClient interface {
	// SendWeatherNotification は天気予報をDiscordに通知します
	SendWeatherNotification(ctx context.Context, in *WeatherNotificationRequest, opts ...grpc.CallOption) (*WeatherNotificationResponse, error)
}

type weatherNotificatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherNotificatorServiceClient(cc grpc.ClientConnInterface) WeatherNotificatorServiceClient {
	return &weatherNotificatorServiceClient{cc}
}

func (c *weatherNotificatorServiceClient) SendWeatherNotification(ctx context.Context, in *WeatherNotificationRequest, opts ...grpc.CallOption) (*WeatherNotificationResponse, error) {
	out := new(WeatherNotificationResponse)
	err := c.cc.Invoke(ctx, "/weather_notificator.WeatherNotificatorService/SendWeatherNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherNotificatorServiceServer is the server API for WeatherNotificatorService service.
// All implementations must embed UnimplementedWeatherNotificatorServiceServer
// for forward compatibility
type WeatherNotificatorServiceServer interface {
	// SendWeatherNotification は天気予報をDiscordに通知します
	SendWeatherNotification(context.Context, *WeatherNotificationRequest) (*WeatherNotificationResponse, error)
	mustEmbedUnimplementedWeatherNotificatorServiceServer()
}

// UnimplementedWeatherNotificatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherNotificatorServiceServer struct {
}

func (UnimplementedWeatherNotificatorServiceServer) SendWeatherNotification(context.Context, *WeatherNotificationRequest) (*WeatherNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWeatherNotification not implemented")
}
func (UnimplementedWeatherNotificatorServiceServer) mustEmbedUnimplementedWeatherNotificatorServiceServer() {
}

// UnsafeWeatherNotificatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherNotificatorServiceServer will
// result in compilation errors.
type UnsafeWeatherNotificatorServiceServer interface {
	mustEmbedUnimplementedWeatherNotificatorServiceServer()
}

func RegisterWeatherNotificatorServiceServer(s *grpc.Server, srv WeatherNotificatorServiceServer) {
	s.RegisterService(&_WeatherNotificatorService_serviceDesc, srv)
}

func _WeatherNotificatorService_SendWeatherNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherNotificatorServiceServer).SendWeatherNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather_notificator.WeatherNotificatorService/SendWeatherNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherNotificatorServiceServer).SendWeatherNotification(ctx, req.(*WeatherNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeatherNotificatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "weather_notificator.WeatherNotificatorService",
	HandlerType: (*WeatherNotificatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWeatherNotification",
			Handler:    _WeatherNotificatorService_SendWeatherNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/weather_notificator/weather_notificator.proto",
}
