// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/weather_notificator/weather_notificator.proto

package weather_notificator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WeatherNotificationRequest は天気通知リクエストを定義します
type WeatherNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`             // OpenWeatherMap API キー
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`                               // 都市名
	MaxDays       int32                  `protobuf:"varint,3,opt,name=max_days,json=maxDays,proto3" json:"max_days,omitempty"`         // 最大日数
	WebhookUrl    string                 `protobuf:"bytes,4,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"` // Discord Webhook URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherNotificationRequest) Reset() {
	*x = WeatherNotificationRequest{}
	mi := &file_proto_weather_notificator_weather_notificator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherNotificationRequest) ProtoMessage() {}

func (x *WeatherNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_notificator_weather_notificator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherNotificationRequest.ProtoReflect.Descriptor instead.
func (*WeatherNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_weather_notificator_weather_notificator_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherNotificationRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *WeatherNotificationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherNotificationRequest) GetMaxDays() int32 {
	if x != nil {
		return x.MaxDays
	}
	return 0
}

func (x *WeatherNotificationRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

// WeatherNotificationResponse は天気通知レスポンスを定義します
type WeatherNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 成功フラグ
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // メッセージ
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // エラーメッセージ（エラー時のみ）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherNotificationResponse) Reset() {
	*x = WeatherNotificationResponse{}
	mi := &file_proto_weather_notificator_weather_notificator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherNotificationResponse) ProtoMessage() {}

func (x *WeatherNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_notificator_weather_notificator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherNotificationResponse.ProtoReflect.Descriptor instead.
func (*WeatherNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_weather_notificator_weather_notificator_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WeatherNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WeatherNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_weather_notificator_weather_notificator_proto protoreflect.FileDescriptor

const file_proto_weather_notificator_weather_notificator_proto_rawDesc = "" +
	"\n" +
	"3proto/weather_notificator/weather_notificator.proto\x12\x13weather_notificator\"\x85\x01\n" +
	"\x1aWeatherNotificationRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x19\n" +
	"\bmax_days\x18\x03 \x01(\x05R\amaxDays\x12\x1f\n" +
	"\vwebhook_url\x18\x04 \x01(\tR\n" +
	"webhookUrl\"g\n" +
	"\x1bWeatherNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x99\x01\n" +
	"\x19WeatherNotificatorService\x12|\n" +
	"\x17SendWeatherNotification\x12/.weather_notificator.WeatherNotificationRequest\x1a0.weather_notificator.WeatherNotificationResponseBDZBgithub.com/landmaster135/devbox/cmd/grpc/proto/weather_notificatorb\x06proto3"

var (
	file_proto_weather_notificator_weather_notificator_proto_rawDescOnce sync.Once
	file_proto_weather_notificator_weather_notificator_proto_rawDescData []byte
)

func file_proto_weather_notificator_weather_notificator_proto_rawDescGZIP() []byte {
	file_proto_weather_notificator_weather_notificator_proto_rawDescOnce.Do(func() {
		file_proto_weather_notificator_weather_notificator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_weather_notificator_weather_notificator_proto_rawDesc), len(file_proto_weather_notificator_weather_notificator_proto_rawDesc)))
	})
	return file_proto_weather_notificator_weather_notificator_proto_rawDescData
}

var file_proto_weather_notificator_weather_notificator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_weather_notificator_weather_notificator_proto_goTypes = []any{
	(*WeatherNotificationRequest)(nil),  // 0: weather_notificator.WeatherNotificationRequest
	(*WeatherNotificationResponse)(nil), // 1: weather_notificator.WeatherNotificationResponse
}
var file_proto_weather_notificator_weather_notificator_proto_depIdxs = []int32{
	0, // 0: weather_notificator.WeatherNotificatorService.SendWeatherNotification:input_type -> weather_notificator.WeatherNotificationRequest
	1, // 1: weather_notificator.WeatherNotificatorService.SendWeatherNotification:output_type -> weather_notificator.WeatherNotificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_weather_notificator_weather_notificator_proto_init() }
func file_proto_weather_notificator_weather_notificator_proto_init() {
	if File_proto_weather_notificator_weather_notificator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_weather_notificator_weather_notificator_proto_rawDesc), len(file_proto_weather_notificator_weather_notificator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weather_notificator_weather_notificator_proto_goTypes,
		DependencyIndexes: file_proto_weather_notificator_weather_notificator_proto_depIdxs,
		MessageInfos:      file_proto_weather_notificator_weather_notificator_proto_msgTypes,
	}.Build()
	File_proto_weather_notificator_weather_notificator_proto = out.File
	file_proto_weather_notificator_weather_notificator_proto_goTypes = nil
	file_proto_weather_notificator_weather_notificator_proto_depIdxs = nil
}
