name: go-test-integration

on:
  push:

permissions: write-all

env:
  GO_VERSION: "1.23"
  COV_FILE: "coverage.out"
  GOOGLE_CLOUD_PROJECT_ID_01: "test-pj"
  GCLOUD_PROJECT_NUMBER: ${{ secrets.GCLOUD_PROJECT_NUMBER }}
  GCLOUD_POOL_ID: ${{ secrets.GCLOUD_POOL_ID }}
  GCLOUD_PROVIDER_ID: ${{ secrets.GCLOUD_PROVIDER_ID }}
  GCLOUD_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          # 特定の組み合わせを除外
          - os: windows-latest
          - os: macos-latest
        include:
          # Set additional parameters for a specific combination
          - os: ubuntu-latest
            coverage-badge: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          sudo apt install -y tesseract-ocr libtesseract-dev libleptonica-dev
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install ffmpeg
          # brew install tesseract leptonica # uninstallable command
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y ffmpeg
          choco install -y tesseract
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check Go version
        run: go version
      - id: "gcloud_auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/${{ env.GCLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.GCLOUD_POOL_ID }}/providers/${{ env.GCLOUD_PROVIDER_ID }}"
          service_account: "${{ env.GCLOUD_SERVICE_ACCOUNT_EMAIL }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Run Test
        run: |
          go test -v ./... -coverpkg=./... -covermode=count -coverprofile=${{ env.COV_FILE }}
          go tool cover -func=${{ env.COV_FILE }} -o=${{ env.COV_FILE }}
      - name: Go Coverage Badge # Pass the `coverage.out` output to this action
        if: ${{ matrix.coverage-badge }}
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: ${{ env.COV_FILE }}
      - name: Push changes
        if: ${{ matrix.coverage-badge }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git log -1
          git diff --cached --quiet || (git commit -m "chore: Updated coverage badge [skip ci]" && git push origin HEAD)
