name: go-test-integration

on:
  push:

permissions: write-all

env:
  GO_VERSION: '1.23'
  COV_FILE: 'coverage.out'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          # 特定の組み合わせを除外
          - os: windows-latest
        include:
          # Set additional parameters for a specific combination
          - os: ubuntu-latest
            coverage-badge: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: installation
        run: |
          apt install ffmpeg -y
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check Go version
        run: go version
      - name: Run Test
        run: |
          go test -v ./... -coverpkg=./... -covermode=count -coverprofile=${{ env.COV_FILE }}
          go tool cover -func=${{ env.COV_FILE }} -o=${{ env.COV_FILE }}
      - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
        if: ${{ matrix.coverage-badge }}
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: ${{ env.COV_FILE }}
      - name: Push changes
        if: ${{ matrix.coverage-badge }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git log -1
          git diff --cached --quiet || (git commit -m "chore: Updated coverage badge." && git push origin HEAD)
